import { BigNumber } from "bignumber.js";
import { Contract, web3 } from "ethers";

const contractABI = [
  {
    "constant": true,
    "inputs": [],
    "name": "getPrice",
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "payable": false,
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "constant": false,
    "inputs": [
      {
        "name": "farmerAddress",
        "type": "address"
      },
      {
        "name": "quantity",
        "type": "uint256"
      }
    ],
    "name": "sellCrop",
    "outputs": [],
    "payable": true,
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "constant": false,
    "inputs": [
      {
        "name": "farmerAddress",
        "type": "address"
      },
      {
        "name": "quantity",
        "type": "uint256"
      }
    ],
    "name": "buyCrop",
    "outputs": [],
    "payable": false,
    "stateMutability": "payable",
    "type": "function"
  }
];

const contractAddress = "0x...";

const contract = new Contract(contractABI, contractAddress, web3.eth);

async function getPrice() {
  const price = await contract.getPrice();
  return price;
}

async function sellCrop(farmerAddress, quantity) {
  await contract.sellCrop(farmerAddress, quantity);
}

async function buyCrop(farmerAddress, quantity) {
  await contract.buyCrop(farmerAddress, quantity);
}

export { getPrice, sellCrop, buyCrop };











